### ISSUE TITLE
Is this the actual implementation of GazeFollow?

### ISSUE THREAD

**Issue by walterwang** [Wiz8910/GazeFollow#1]
Was looking though the tensorflow code, it seems like a very basic implementation of a convnet. Was wondering if this is an actual implementation of GazeFollow paper? Thank you

**Comment by ColinConduff** [comment]
You can find the actual implementation at http://gazefollow.csail.mit.edu/.  We were just implementing a few machine learning methods that we had learned about in a Computer Vision course and comparing our results to the original authors' results.  I'll see if I can change the name of our GitHub project.

**Comment by ColinConduff** [comment]
Hey @Wiz8910, I don't have admin privileges to change the name of the repo.  It looks like it's confusing people that are trying to find the original authors' implementation.  Can you change it?

**Comment by walterwang** [comment]
ok no worries, thank you

**Comment by Wiz8910** [comment]
Yeah, we could've chose a better name, now it has one super generic

On Mon, May 29, 2017 at 11:14 AM, WalterWangNYUMLC <notifications@github.com
